before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/parca-load/
    id: "parca-load"
    binary: parca-load
    # https://goreleaser.com/customization/build/#reproducible-builds
    mod_timestamp: "{{ .CommitTimestamp }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
      - -v
    ldflags:
      # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
      - -X main.version={{.Version}} -X main.commit={{.Commit}}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
source:
  enabled: true
